### ISSUE TITLE
refactor large switch statement

### ISSUE THREAD

**Issue by geoolson** [geoolson/TheRoyalDiamond#2]
There's a large switch statement that's over100 lines long in function map_string in map.js. Many of the cases use the same string with only one character changed. This switch statement can be reduced significantly and modern string templating with backticks can help reduce the repetitive code further. The switch statement could easily be replaced with a dictionary/js object using keys for the cases and return the value to append to the result.

**Comment by njon2** [comment]
This issue was resolved with PR #3 .
